# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Moya', '~> 15.0'
target 'scg_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for scg_test

  target 'scg_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'scg_testUITests' do
    # Pods for testing
  end

end
